## Python

Разберем применение метода инструментальных переменных на **python**.
```{r, include=FALSE}
library(reticulate)
use_python('/Users/Sasha/anaconda3/bin/python3')
```

Загружаем необходимые библиотеки:
```{python}
import pandas as pd # работы с панельными данными
import seaborn as sns # визуализация
import matplotlib.pyplot as plt # визуализация
import statsmodels.api as sm # реализация двухшагового МНК
```

Загружаем данные и исследуем их строение:
```{python}
url = 'https://raw.githubusercontent.com/arunk13/MSDA-Assignments/master/IS607Fall2015/Assignment3/student-mat.csv'
df = pd.read_csv(url, 
                header=0,
                sep = ';') 
print(df.head(2))
```

Изучим зависимость успеваемости ученика `G3` от времени, которое он тратит на учебу `studytime` и его свободного времени `freetime`, а в качестве инструмента для свободного времени используем `traveltime`, время, которое он тратит на поездку до учебы. Логика здесь такая: чем больше времени ученик тратит на дорогу, тем меньше у него времени остается на учебу, а значит, меньше вероятность получить хорошую оценку. Преобразуем выбранные переменные:
```{python}
grade = df.loc[:, 'G3']
freetime = df.loc[:, 'freetime']
traveltime = df.loc[:, 'traveltime']
studtytime = df.loc[:, 'studytime']
```

Проверим корреляцию переменной `freetime` и подобранного инструмента `traveltime`, построив диаграмму корреляции всех признаков:
```{python}
colormap = plt.cm.viridis 
corr = df.corr()
plt.figure(figsize=(12,12))
plt.title('Корреляционная матрица признаков', y=1.02, size=15)
sns.heatmap(corr,linewidths=0.1,vmax=1.0, square=True, cmap=colormap, linecolor='white', annot=True)
```

Корреляция между переменными составляет 0.1, а корреляция инструмента с целевой переменной -0.12, что, в принципе, нас вполне устраивает.

Проведем двухшаговый МНК при помощи функции IV2SLS из пакета **linearmodels**. Чтобы использовать ее, надо установить пакет **linearmodels**. Для этого, если он еще не установлен, нужно выполнить следующую команду в командной строке: `pip install linearmodels`. Убедившись, что она установлена, импортируем нужные библиотеки и приступаем к двухшаговому МНК:
```{python}
from linearmodels import IV2SLS
ivmod = IV2SLS.from_formula('grade ~ 1 + studytime  + [freetime ~ traveltime]', df)
res_2sls = ivmod.fit()
print(res_2sls.summary)
```

Проверим качество подбора инструментов с помощью тестов.
*Durbin тест*:
```{python}
res_2sls.durbin()
```
*Wu-Hausman тест*:
```{python}
res_2sls.wu_hausman()
```

Основная гипотеза об экзогенности инструментов в обоих тестах отвергается, значит, мы выбрали подходящие инструменты.