## Stata

```{stata, include=FALSE}
clear all
```

Будем работать с набором данных, содержащих информацию о зарплатах. Загрузим данные, посмотрим их строение.
```{stata}
webuse educwages
describe
```

Проведем двухшаговый МНК с помощью функции *ivregress*. В качестве зависимой переменной djpmмем зарплату (`wages`), в качестве регрессора - образование (`education`). В качестве инструментов для образования используем образование отца (`feducation`), образование матери (`meducation`) и участие в профсоюзе (`union`).
```{stata}
ivregress 2sls wages union (education = meducation feducation) 
```

Проведем тесты на качество подбора инструментов.
```{stata}
estat endog
```

Основная гипотеза об экзогенности отвергается, что означает, что выбранные инструменты эндогенны. *Тест Durbin* и *тест Wu-Hausman* также показывают, что выбранные инструменты подходят.

Проведем *тесты Sargan и Basmann*.
```{stata}
estat overid
```

Нулевая гипотеза в *тесте Sargan* и *тесте Basmann на сверхидентифицирующие ограничения* отвергается тогда, когда хотя бы один из инструментов не подходит. Так как нулевая гипотеза не отвергается на любом разумном уровне значимости, наши инструменты были подобраны хорошо.