---
title: "Проектик"
author: "Ася"
date: '7 марта 2019 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Нужные пакеты в питоне - statsmodels, linearmodels.

###Темы
1. Простая регрессия
2. Модели бинарного выбора
3. Модели упорядоченного выбора
4. Пуассоновская регрессия
5. Модель неупорядоченного выбора
6. Инструменты для простой регрессии
7. ARMA
8. Простые модели панельных данных (Random effect, fixed effect, pooled, difference/indiffence)
9. Гетероскедастичность в простой регрессии
10. МГК

**Продвинутые сюжеты**

1. Динамические панели (Arellano-Bond, Blundell-Bond)
2. TOBIT, HECKIT
3. Treatment effects


**И еще кое-что:**

+ раздел "Шишки и грабли"

+ Коан про русских панд (русские переменные, чтобы работали и на линухе, и на маке, и на винде). По-разному сохранять эксель, чтобы везде открылось

+ **Словарик!!!** с командами из статы в питон и в r + ссылки на примеры использования в буке

___

###План

1 шаг: сотавить схему хаоса, список статовских команд, в каких они файлах, что предложено в виде решения

2 шаг: разнести команды по коанам

3 шаг: начать писать коаны

**Прикольно называем коаны!**. Например, Притча о простой регрессии/куан

**Пишем стильно!** В R поможет *styler.*


Нужные пакеты в питоне - statsmodels, linearmodels.


___


###Хотим

1. Книжечка (букдаун)

2. Самый лучший коан сделать в формате плаката a1 и повесить в качестве агитки


___

**На следующий раз:**

составить список команд, каркас бук, первый коан