## Python

Загрузим yужные пакетики.

```{python}
import pandas as pd # работа с таблицами
import numpy as np # математика, работа с матрицами
import matplotlib.pyplot as plt # графики
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.graphics.gofplots as gf
from statsmodels.stats.outliers_influence import summary_table
import seaborn as sns # еще более классные графики
from scipy.stats import shapiro # еще математика
import statsmodels.discrete.discrete_model
from statsmodels.discrete.count_model import ZeroInflatedPoisson

plt.style.use('ggplot')
```

Загружаем данные и смотрим описательные статистики.

```{python}
df_fish = pd.read_stata('../data/05_fish.dta')
```

Посмотрим, как выглядит распределение объясняемой переменной. 

```{python}
sns.distplot(df_fish['count'])
plt.show()
```

Превращаем переменную `camper` в категориальную.

```{python}
df_fish['camper'] = df_fish['camper'].astype('category')
```

Строим Пуассоновскую регрессию.

```{python}
regr_pois = smf.glm('count ~ child + camper +  persons', data=df_fish,
                    family=sm.families.Poisson()).fit()
regr_pois.summary()
```

Посмотрим, равны ли среднее значение и дисперсия, как это предполагает распределение Пуассона.
```{python}
(df_fish
 .filter(['count', 'camper'])
 .groupby('camper')
 .agg(['mean', 'var']))
```

И регрессию с остатками, имеющими отрицательное биномиальное распределение.
```{python}                
regr_bin = smf.glm('count ~ child + camper +  persons', data=df_fish,
              family=sm.families.NegativeBinomial()).fit()

regr_bin.summary()
```
 
Проверим гипотезу о равенстве 0 коэффициента при переменной `camper`. Для этого проведем тест Вальда.

```{python}
hyp = '(child = 0)'
regr_bin.wald_test(hyp)
```
Видим, что p-value очень маленькое. Значит, гипотеза о незначимости коэффициента при переменной `camper` отвергается.

Посчитаем средний предельный эффект для каждой переменной.

```{python}                
pred = regr_pois.fittedvalues
mean_mef_child = np.mean([regr_pois.params[1]*p for p in pred])
mean_mef_camper = np.mean([regr_pois.params[2]*p for p in pred])

data_1 = pd.DataFrame({'child': df_fish['child'], 'camper': 1, 'persons': df_fish['persons']})
data_0 = pd.DataFrame({'child': df_fish['child'], 'camper': 0, 'persons': df_fish['persons']})
mean_mef_persons = np.mean([(regr_pois.predict(data_1)[i]-regr_pois.predict(data_0)[i]) 
                            for i in range(len(df_fish))])
```

```{python}
#plot_model(regr_pois, type='effect', terms='camper')
```


И модель с раздутыми нулями. (которая у меня не получилась :( )
